version: '3'
services:
  app_service:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
#
#  nginx-reverse-proxy:
#    image: nginx:1.25.2
#    ports:
#      - 443:443
#      - 80:80
#    volumes:
#      - ./nginx_config_deployment.conf:/etc/nginx/conf.d/default.conf
#    depends_on:
#      - argies_service
